#!/bin/bash
kaggle datasets download killbot/linkedin-profiles-and-jobs-data
kaggle datasets download omashish/linkedin-profile-data
kaggle datasets download killbot/linkedin
kaggle datasets download rhuebner/human-resources-data-set
kaggle datasets download shashankshukla123123/linkedin-job-data
kaggle datasets download stitch/hr-data-for-mldloptimization-practice
kaggle datasets download proxycurl/linkedin-dataset-singapore-people-profiles
kaggle datasets download proxycurl/linkedin-dataset-india-people-profiles
kaggle datasets download proxycurl/10000-canadian-people-profiles
kaggle datasets download joebeachcapital/technology-mergers-and-acquisitions
kaggle datasets download revathyta/survey-on-employment-trends
kaggle datasets download proxycurl/linkedin-dataset-denmark-people-profiles
kaggle datasets download proxycurl/singapore-companies
kaggle datasets download shrashtisinghal/data-science-social-groups-survey
kaggle datasets download architty108/github-indian-users-deep-data
kaggle datasets download shashankshukla123123/linkedin-job-data
kaggle datasets download proxycurl/10000-us-people-profiles
kaggle datasets download proxycurl/10000-israel-people-profiles
kaggle datasets download proxycurl/linkedin-dataset-japan-people-profiles
kaggle datasets download gabriellisboa/linkedin-brasil-web-scraping
kaggle datasets download gabriellisboa/linkedin-brasil-web-scraping
kaggle datasets download proxycurl/10000-us-company-profiles
kaggle datasets download manishkumar7432698/linkedinuserprofiles